baseURL = "https://yursan.id/"			# Site's URL
title = "Yurizal Susanto"					# Site's Name
theme = "manis"
copyright = "&copy; 2019 Yurizal Susanto"	# Copyright notice. Note: You can use HTML tag here
pluralizeListTitles = false
paginate = 10								# Minimum number of item before paginate navigation show up
canonifyURL = true
defaultContentLanguage = "in"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
	tag = "tags"

[menu]
	[[menu.main]]
	identifier = "about"
	name = "Tentang"
	url = "/about"

	[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/blog"

	[[menu.main]]
	identifier = "work"
	name = "Karya"
	url = "/work"


[params]
	# Custom CSS
	customCSS = []

	description = "Tempat saya kembali berpikir, jika kode sudah tidak berfungsi lagi."
	tagline = "Pandangan awam pemula"
	themeAttrib = true
	licenseURL = "/about/lisensi"

	# 404 Configuration
	head404 = "Maaf, halaman yang anda inginkan tidak dapat ditemukan."
	sub404 = "Kembali ke halaman <a href='http://yurizal-san.com'>Utama</a>."

	colorTheme = "#1eacfb"
	latestCount = 3
	faviconImg = ""
	dateFmt = "Jan 02, 2006"
	
	# Section Configuration
	mainSections = ["blog"]
	workSections = ["work"]
	utterancesSections = [ "blog" ]
	
	# Utterances Configuration
	utterancesRepo = "https://github.com/yursan9/awkward-penguin"
	utterancesTheme = "github-light"
	utterancesLabel = "comment"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "yursan9@pm.me"
	github = "https://github.com/yursan9/"

# Edit the language if you want to translate your blog
[languages.in]
	lang = "in"
	languageName = "Bahasa Indonesia"
	weight = 1
#[languages.en]
#    lang = "en"
#    languageName = "English"
#    weight = 0
