backend:
    name: git-gateway
    branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://yursan.id
site_url: https://yursan.id
publish_mode: editorial_workflow
show_preview_links: true

collections:
    - name: "blog"
      label: "Blog"
      folder: "content/blog"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "date"}
        - {label: "Tags", name: "tags", widget: "list"}
        - {label: "Draft", name: "draft", widget: "boolean", default: true}
        - {label: "Body", name: "body", widget: "markdown"}

    - name: "karya"
      label: "Karya"
      folder: "content/work"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "date"}
        - {label: "Tags", name: "tags", widget: "list"}
        - {label: "Draft", name: "draft", widget: "boolean", default: true}
        - {label: "Homepage URL", name: "workURL", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}

    - name: "tentang"
      label: "Tentang"
      folder: "content/about"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "date"}
        - {label: "Draft", name: "draft", widget: "boolean", default: true}
        - {label: "Body", name: "body", widget: "markdown"}
